theme: jekyll-theme-primer
title: The ultimate dotfiles
description: a streamlined configuration of GNU/Linux
github:
    private: false
    license:
        name: GPL-3.0
    source:
        branch: "master"
        path: "/"
    repository_url: "https://github.com/matteogiorgi/.minidot"
