title: `.minidot`: the ultimate dotfiles
description: a streamlined configuration of `GNU/Linux`
theme: jekyll-theme-primer

github:
    private: false
    license:
        name: GPL-3.0
    source:
        branch: "master"
        path: "/"
    repository_url: "https://github.com/matteogiorgi/.minidot"
