colorscheme desertex

set-option global tabstop 4
set-option global indentwidth 4
set-option global scrolloff 8,16
set-option global ui_options ncurses_status_on_top=true
# ---
add-highlighter global/ number-lines -relative -hlcursor
add-highlighter global/ regex \h+$ 0:Error
add-highlighter global/ wrap -word -indent
add-highlighter global/ show-matching
# ---
map -docstring "yank the selection into the clipboard" global user y "<a-|> xsel -i<ret>"
map -docstring "paste the clipboard" global user p "<a-!> xsel<ret>"
